# Generated by Django 4.1.2 on 2022-11-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos', models.ManyToManyField(null=True, to='core.aluno', verbose_name='Alunos')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso', verbose_name='Curso')),
                ('periodo_inicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Vinculo',
                'verbose_name_plural': 'Vinculos',
            },
        ),
    ]
