# Generated by Django 4.1.2 on 2022-11-03 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodo', verbose_name='Período'),
        ),
    ]
