# Generated by Django 4.1.2 on 2022-11-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('Cadastrando', 'Cadastrando'), ('Cadastro Finalizado', 'Cadastro Finalizado'), ('Andamento', 'Andamento'), ('Concluído', 'Concluído'), ('Cancelada', 'Cancelada')], default=('Cadastrando', 'Cadastrando'), max_length=100, verbose_name='Status'),
        ),
    ]
