# Generated by Django 4.1.2 on 2022-11-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_turma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
