# Generated by Django 4.1.2 on 2022-11-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_blocosalas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocosalas',
            options={'verbose_name': 'Bloco de Salas', 'verbose_name_plural': 'Blocos de Salas'},
        ),
    ]
