# Generated by Django 4.1.2 on 2022-11-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_blocosalas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='bloco_salas',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blocosalas', verbose_name='Bloco de Salas'),
        ),
    ]
