# Generated by Django 4.1.2 on 2022-11-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_turma_professor_turma_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='horario',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='horario'),
        ),
    ]
