# Generated by Django 4.1.2 on 2022-11-13 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_turma_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='bloco_salas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blocosalas', verbose_name='Bloco de Salas'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala', verbose_name='Sala'),
        ),
    ]
