# Generated by Django 4.1.2 on 2022-11-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_sala_bloco_salas_alter_turma_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='situacao',
            field=models.CharField(choices=[('Reprovado', 'Reprovado'), ('Aprovado', 'Aprovado'), ('Em andamento', 'Em andamento')], default='Em andamento', max_length=100, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
    ]
