# Generated by Django 4.1.2 on 2022-11-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_noticiaturma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaturma',
            options={'ordering': ['data_atualizacao', '-id'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
    ]
