# Generated by Django 4.1.2 on 2022-11-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_noticiaturma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/files/', verbose_name='Anexo')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Tarefa da Turma',
                'verbose_name_plural': 'Tarefas da Turma',
            },
        ),
    ]
