# Generated by Django 4.1.2 on 2022-11-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tarefaturma_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='nota_recuperacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Nota da Recuperacao'),
        ),
    ]
